version: '3'

services:
  app:
    build: .
    working_dir: /app/polyglot-ssr-app
    command: bash ./start.sh
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - ~/.ivy2:/root/.ivy2
      - ~/.sbt:/root/.sbt
      - ~/.coursier:/root/.coursier
